package register

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// AgentConfig represents the configuration to be written.
type AgentConfig struct {
	ServerURL   string
	DeviceToken string
	WatchPaths  []string
	DBPath      string
}

const configTemplate = `# flora-agent configuration file
# Generated by: flora-agent register

# Server configuration
server:
  # flora-server URL
  url: "{{.ServerURL}}"

  # Device authentication token
  device_token: "{{.DeviceToken}}"

# Directory monitoring configuration
watch:
  # Directories to watch for recording files
  paths:
{{- range .WatchPaths}}
    - {{.}}
{{- end}}

  # File pattern matching
  patterns:
    # File patterns to include (glob syntax)
    include:
      - "*.mcap"
      - "*.bag"
      - "*.db3"
    # File patterns to exclude (glob syntax)
    exclude:
      - "*.active"      # Files being actively written
      - "*.tmp"
      - "*~"
      - "*.part"

  # Interval for periodic directory scans (reconciliation)
  scan_interval: 30s

  # Minimum file age before processing (avoid incomplete files)
  min_file_age: 5s

# Upload configuration
upload:
  # Enable/disable uploads
  enabled: true
  # Number of concurrent uploads
  concurrent: 2
  # Chunk size for multipart uploads (bytes)
  chunk_size: 10485760  # 10MB
  # Number of retry attempts for failed uploads
  retry_attempts: 3
  # Delay between retries
  retry_delay: 5s
  # Bandwidth limit (bytes/sec, 0 = unlimited)
  bandwidth_limit: 0

# Local storage configuration
storage:
  # SQLite database path for state persistence
  db_path: {{.DBPath}}

# Prometheus metrics configuration (optional)
metrics:
  enabled: false
  port: 9090
  path: /metrics

# Health check endpoint configuration
health:
  # Enable/disable health check HTTP endpoint
  enabled: true
  # Port for health check server
  port: 8080
  # Path for main health check endpoint
  # Additional endpoints: /livez (liveness), /readyz (readiness)
  path: /health

# Logging configuration
log:
  # Log level: debug, info, warn, error
  level: info
  # Log format: json, text
  format: json
  # Output: stdout, file
  output: stdout
`

// WriteConfigFile writes the agent configuration to a file.
func WriteConfigFile(configPath string, config *AgentConfig) error {
	// Ensure directory exists
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Create template
	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse config template: %w", err)
	}

	// Create file
	file, err := os.Create(configPath)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	// Set file permissions (readable by owner only due to sensitive token)
	if err := file.Chmod(0600); err != nil {
		return fmt.Errorf("failed to set config file permissions: %w", err)
	}

	// Execute template
	if err := tmpl.Execute(file, config); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	return nil
}

// DefaultConfigPath returns the default configuration file path.
func DefaultConfigPath() string {
	// Use /etc/flora-agent for system installation on Linux
	if os.Getuid() == 0 {
		return "/etc/flora-agent/agent.yaml"
	}

	// Use user config directory for non-root
	home, err := os.UserHomeDir()
	if err != nil {
		return "./agent.yaml"
	}
	return filepath.Join(home, ".config", "flora-agent", "agent.yaml")
}

// DefaultDBPath returns the default database path.
func DefaultDBPath() string {
	// Use /var/lib for system installation on Linux
	if os.Getuid() == 0 {
		return "/var/lib/flora-agent/agent.db"
	}

	// Use user data directory for non-root
	home, err := os.UserHomeDir()
	if err != nil {
		return "./agent.db"
	}
	return filepath.Join(home, ".local", "share", "flora-agent", "agent.db")
}
